-- The partial unique expression index created in
-- 20261006110514_internal_tasks_open_action_fingerprint.sql is also the
-- canonical lookup index for metadata->>'action_fingerprint'.
-- No additional JSONB GIN index is required.
